namespace API.DTO
{
    public class StaffProfileUpdateDTO
    {
        public long? Id { get; set; }
        public long? BankId { get; set; }
        public string? ItimeId { get; set; }
        public long? BankId2 { get; set; }
        public long? BankBranchId { get; set; }
        public long? BankBranchId2 { get; set; }
        public string? BankNo2 { get; set; }
        public string? BankNo { get; set; }

        public long? OrgId { get; set; }
        public long? ObjectEmployeeId { get; set; }
        public bool? IsNotContract { get; set; }
        public long? PositionId { get; set; }
        public long? GenderId { get; set; }
        public long? NationId { get; set; }
        public string? OtherName { get; set; }
        public long? NationalityId { get; set; }
        public long? ReligionId { get; set; }
        public string? Relations { get; set; }
        public string? YellowFlag { get; set; }
        public long? MaritalStatusId { get; set; }
        public string? BirthRegisAddress { get; set; }
        public string? Domicile { get; set; }
        public string? IdentityNumber { get; set; }
        public long? IdentityNumberAddress { get; set; }
        public string? TaxCode { get; set; }
        public long? TaxCodeAddress { get; set; }
        public string? BloodGroup { get; set; }
        public string? BirthPlace { get; set; }
        public string? BloodPressure { get; set; }
        public string? Height { get; set; }
        public string? Weight { get; set; }
        public string? HeathType { get; set; }
        public string? LeftEye { get; set; }
        public string? RightEye { get; set; }
        public string? Heart { get; set; }
        public string? HealthNote { get; set; }
        public DateTime? DateExam { get; set; }

        public DateTime? BirthDay { get; set; }
        public DateTime? TaxCodeDate { get; set; }
        public DateTime? IdentityNumberDate { get; set; }

        public string? Passport { get; set; }
        public string? PassAddress { get; set; }
        public string? Visa { get; set; }
        public string? VisaAddress { get; set; }
        public string? LaborBookNumber { get; set; }
        public DateTime? PassDateExpired { get; set; }
        public DateTime? LaborBookDate { get; set; }
        public DateTime? LaborBookDateExpired { get; set; }
        public string? LaborBookAddress { get; set; }
        public string? HealthNotes { get; set; }
        public string? Carrer { get; set; }
        public long? InsArea { get; set; }
        public string? InsNumber { get; set; }
        public string? HealthCareAddress { get; set; }
        public string? InsCardNumber { get; set; }
        public string? FamilyMember { get; set; }
        public string? FamilyPolicy { get; set; }
        public string? Veterans { get; set; }
        public string? PoliticalTheory { get; set; }
        public string? CareerBeforeRecruitment { get; set; }
        public string? TitleConferred { get; set; }
        public string? SchoolOfWork { get; set; }
        public string? PrisonNote { get; set; }
        public string? FamilyDetail { get; set; }
        public bool? IsUnionist { get; set; }
        public string? UnionistPosition { get; set; }
        public DateTime? UnionistDate { get; set; }
        public string? UnionistAddress { get; set; }
        public bool? IsJoinYouthGroup { get; set; }
        public bool? IsMember { get; set; }
        public string? MemberPosition { get; set; }
        public string? MemberAddress { get; set; }
        public DateTime? MemberDate { get; set; }
        public DateTime? MemberOfficalDate { get; set; }
        public string? LivingCell { get; set; }
        public string? CardNumber { get; set; }
        public string? PoliticalTheoryLevel { get; set; }
        public string? ResumeNumber { get; set; }
        public DateTime? VateransMemberDate { get; set; }
        public string? VateransPosition { get; set; }
        public string? VateransAddress { get; set; }
        public long? GovernmentManagementId { get; set; }
        public string? YouthGroupPosition { get; set; }
        public DateTime? YouthGroupDate { get; set; }
        public DateTime? EnlistmentDate { get; set; }
        public DateTime? DischargeDate { get; set; }
        public DateTime? YouthSaveNationDate { get; set; }
        public string? YouthGroupAddress { get; set; }
        public string? HighestMilitaryPosition { get; set; }
        public string? CurrentPartyCommittee { get; set; }
        public string? PartytimePartyCommittee { get; set; }
        public string? YouthSaveNationPosition { get; set; }
        public string? YouthSaveNationAddress { get; set; }
        public DateTime? VisaDate { get; set; }
        public DateTime? VisaDateExpired { get; set; }
        public DateTime? PassDate { get; set; }
        public long? EducationLevelId { get; set; }
        public long? LearningLevelId { get; set; }
        public string? ComputerSkill { get; set; }
        public string? License { get; set; }
        public long? LicenseId { get; set; }
        public long? QualificationId { get; set; }
        public long? QualificationId2 { get; set; }
        public long? QualificationId3 { get; set; }
        public long? TrainingFormId { get; set; }
        public long? TrainingFormId2 { get; set; }
        public long? TrainingFormId3 { get; set; }
        public long? SchoolId { get; set; }
        public long? SchoolId2 { get; set; }
        public long? SchoolId3 { get; set; }
        public long? LanguageId { get; set; }
        public long? LanguageId2 { get; set; }
        public long? LanguageId3 { get; set; }
        public long? LanguageLevelId { get; set; }
        public long? LanguageLevelId2 { get; set; }
        public long? LanguageLevelId3 { get; set; }
        public long? Presenter { get; set; }
        public string? PresenterAddress { get; set; }
        public string? PresenterPhoneNumber { get; set; }
        public bool? IsHost { get; set; }
        public string? HouseholdCode { get; set; }
        public string? HouseholdNumber { get; set; }
        public string? Address { get; set; }
        public string? CurAddress { get; set; }
        public long? ProvinceId { get; set; }
        public long? CurProvinceId { get; set; }
        public long? WardId { get; set; }
        public long? CurWardId { get; set; }
        public long? DistrictId { get; set; }
        public long? CurDistrictId { get; set; }
        public string? Telephone { get; set; }
        public string? LandlinePhone { get; set; }
        public string? EmailCompany { get; set; }
        public string? EmailPersonal { get; set; }
        public string? MainIncome { get; set; }
        public string? OtherSources { get; set; }
        public string? LandGranted { get; set; }
        public string? TaxGrantedHouse { get; set; }
        public string? TotalArea { get; set; }
        public string? SelfPurchaseLand { get; set; }
        public string? SelfBuildHouse { get; set; }
        public string? TotalAppArea { get; set; }
        public string? LandForProduction { get; set; }
        public string? AdditionalInformation { get; set; }
        public long? ComputerSkillId { get; set; }
    }
}
