using CORE.Services.File;

namespace API.DTO
{
    public class StaffProfileEditDTO
    {
        public long? Id { get; set; }
        public string? Avatar { get; set; }
        public long? OrgId { get; set; }
        public string? Name { get; set; }
        public string? OtherName { get; set; }
        public string? ItimeId { get; set; }
        public string? CareerBeforeRecruitment { get; set; }
        public string? Code { get; set; }
        public string? ComCode { get; set; }
        public string? ProfileCode { get; set; }
        public long? TitlePosition { get; set; }
        public string? Company { get; set; }
        public string? AddressWorking { get; set; }
        public string? ComputerSkill { get; set; }
        public long? ComputerSkillId { get; set; }
        public string? License { get; set; }
        public long? LicenseId { get; set; }
        public string? CurAddress { get; set; }
        public string? Telephone { get; set; }
        public long? EmployeeObjectId { get; set; }
        public long? EducationLevelId { get; set; }
        public bool? IsNotContract { get; set; }
        public long? LearningLevelId { get; set; }
        public long? QualificationId { get; set; }
        public long? QualificationId2 { get; set; }
        public long? QualificationId3 { get; set; }
        public long? TrainingFormId { get; set; }
        public long? TrainingFormId2 { get; set; }
        public long? TrainingFormId3 { get; set; }
        public long? SchoolId { get; set; }
        public long? SchoolId2 { get; set; }
        public long? SchoolId3 { get; set; }
        public long? LanguageId { get; set; }
        public long? LanguageId2 { get; set; }
        public long? LanguageId3 { get; set; }
        public long? LanguageLevelId { get; set; }
        public long? LanguageLevelId2 { get; set; }
        public long? LanguageLevelId3 { get; set; }
        public long? Presenter { get; set; }
        public string? PresenterPhoneNumber { get; set; }
        public string? PresenterAddress { get; set; }
        public bool? IsHost { get; set; }
        public bool? IsUnionist { get; set; }
        public string? HouseholdNumber { get; set; }
        public string? UnionistPosition { get; set; }
        public DateTime? UnionistDate { get; set; }
        public DateTime? YouthSaveNationDate { get; set; }
        public string? HouseholdCode { get; set; }
        public string? YouthSaveNationPosition { get; set; }
        public string? YouthSaveNationAddress { get; set; }
        public bool? IsMember { get; set; }
        public string? MemberPosition { get; set; }
        public DateTime? MemberDate { get; set; }
        public string? UnionistAddress { get; set; }
        public string? MemberAddress { get; set; }
        public string? LivingCell { get; set; }
        public string? CardNumber { get; set; }
        public string? PoliticalTheoryLevel { get; set; }
        public string? ResumeNumber { get; set; }
        public string? VateransPosition { get; set; }
        public string? VateransAddress { get; set; }
        public DateTime? EnlistmentDate { get; set; }
        public DateTime? DischargeDate { get; set; }
        public DateTime? VateransMemberDate { get; set; }
        public string? Address { get; set; }
        public DateTime? MemberOfficalDate { get; set; }
        public string? HighestMilitaryPosition { get; set; }
        public string? CurrentPartyCommittee { get; set; }
        public string? PartytimePartyCommittee { get; set; }
        public long? ProvinceId { get; set; }
        public long? CurProvinceId { get; set; }
        public long? DistrictId { get; set; }
        public long? CurDistrictId { get; set; }
        public string? Department { get; set; }
        public long? WardId { get; set; }
        public long? CurWardId { get; set; }
        public string? LandlinePhone { get; set; }
        public string? EmailCompany { get; set; }
        public string? EmailPersonal { get; set; }
        public long? BankId { get; set; }
        public long? BankId2 { get; set; }
        public long? BankBranchId { get; set; }
        public long? BankBranchId2 { get; set; }
        public string? BankNo { get; set; }
        public string? BankNo2 { get; set; }
        public string? TaxGrantedHouse { get; set; }
        public string? SelfPurchaseLand { get; set; }
        public string? MainIncome { get; set; }
        public string? OtherSources { get; set; }
        public string? LandGranted { get; set; }
        public string? TaxtGrantedHouse { get; set; }
        public string? TotalArea { get; set; }
        public string? SelfPurchasedLand { get; set; }
        public string? SelfBuildHouse { get; set; }
        public string? TotalAppArea { get; set; }
        public string? LandForProduction { get; set; }
        public string? AdditionalInformation { get; set; }
        public long? InsurenceAreaId { get; set; }
        public string? DirectManagementPosition { get; set; }
        public string? DirectManagement { get; set; }
        public long? DirectManagementId { get; set; }
        public long? GenderId { get; set; }
        public DateTime? BirthDay { get; set; }
        public long? NationId { get; set; }
        public long? NationalityId { get; set; }
        public string? BirthRegisAddress { get; set; }
        public string? Domicile { get; set; }
        public string? BirthAddress { get; set; }
        public long? ReligionId { get; set; }
        public long? MaritalStatusId { get; set; }
        public string? IdentityNumber { get; set; }
        public DateTime? IdentityNumberDate { get; set; }
        public long? IdentityNumberAddress { get; set; }
        public string? TaxCode { get; set; }
        public DateTime? TaxCodeDate { get; set; }
        public long? TaxCodeDateAddress { get; set; }
        public string? BloodGroup { get; set; }
        public string? Height { get; set; }
        public string? Weight { get; set; }
        public string? BloodPressure { get; set; }
        public string? HealthType { get; set; }
        public string? LeftEye { get; set; }
        public string? RightEye { get; set; }
        public string? Heart { get; set; }
        public DateTime? DateMedicalExam { get; set; }
        public string? HealthNotes { get; set; }
        public string? Passport { get; set; }
        public DateTime? PassportDate { get; set; }
        public DateTime? PassportDateExperiod { get; set; }
        public string? PassportAddress { get; set; }
        public string? Visa { get; set; }
        public DateTime? VisaDate { get; set; }
        public DateTime? VisaDateExperiod { get; set; }
        public string? VisaAddress { get; set; }
        public string? LaborBookNumber { get; set; }
        public DateTime? LaborBookDate { get; set; }
        public DateTime? LaborBookDateExperiod { get; set; }
        public string? LaborBookAddress { get; set; }
        public string? Career { get; set; }
        public string? InsurenceArea { get; set; }
        public string? InsurenceNumber { get; set; }
        public string? MedicalExamPlace { get; set; }
        public string? InsurenceCardNumber { get; set; }
        public string? FamilyMember { get; set; }
        public string? FamilyMatters { get; set; }
        public string? Veterans { get; set; }
        public string? SocialTheory { get; set; }
        public string? TitleConferred { get; set; }
        public string? ForteWork { get; set; }
        public string? NotePrison { get; set; }
        public string? Relatives { get; set; }
        public string? Relations { get; set; }
        public string? YellowFlag { get; set; }
        public string? AvatarFileData { get; set; }
        public string? AvatarFileName { get; set; }
        public string? AvatarFileType { get; set; }
        public DateTime? YouthGroupDate { get; set; }
        public string? YouthGroupAddress { get; set; }
        public string? YouthGroupPosition { get; set; }
        public bool? IsJoinYouthGroup { get; set; }
    }
}
