using API.Main;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Entities;
[Table("AT_TIME_TIMESHEET_DAILY")]
public class AT_TIME_TIMESHEET_DAILY : BASE_ENTITY
{
    public long? EMPLOYEE_ID { get; set; }
    public long? ORG_ID { get; set; }
    public long? POSITION_ID { get; set; }
    public long? PERIOD_ID { get; set; }
    public DateTime? WORKINGDAY { get; set; }
    public string? SHIFT_CODE { get; set; }
    public string? LEAVE_CODE { get; set; }
    public double? LATE { get; set; }
    public double? COMEBACKOUT { get; set; }
    public double? WORKDAY_OT { get; set; }
    public double? WORKDAY_NIGHT { get; set; }
    public string? TYPE_DAY { get; set; }
    public string? CREATED_LOG { get; set; }
    public string? UPDATED_LOG { get; set; }
    public DateTime? VALIN1 { get; set; }
    public DateTime? VALIN2 { get; set; }
    public DateTime? VALIN3 { get; set; }
    public DateTime? VALIN4 { get; set; }
    public long? DECISION_ID { get; set; }
    public long? PA_OBJECT_SALARY_ID { get; set; }
    public long? SHIFT_ID { get; set; }
    public long? MANUAL_ID { get; set; }
    public long? LEAVE_ID { get; set; }
    public double? WORKINGHOUR { get; set; }
    public double? WORKINGHOUR_SHIFT { get; set; }
    public long? NUMBER_SWIPE { get; set; }
    public double? MINUTE_DM_VIPHAM { get; set; }
    public bool? IS_GIAITRINH { get; set; }
    public double? MANUAL_ID_TK { get; set; }
    public double? LEAVE_ID_TK { get; set; }
    public string? LEAVE_CODE_TK { get; set; }
    public double? DIMUON_VESOM_THUCTE { get; set; }
    public double? OT_WEEKDAY { get; set; }
    public double? OT_WEEKNIGHT { get; set; }
    public double? OT_SUNDAY { get; set; }
    public double? OT_SUNDAYNIGHT { get; set; }
    public double? OT_HOLIDAY { get; set; }
    public double? OT_HOLIDAY_NIGHT { get; set; }
    public double? OT_TOTAL_CONVERT { get; set; }
    public double? OT_WEEKDAY_TC { get; set; }
    public double? OT_WEEKNIGHT_TC { get; set; }
    public double? OT_SUNDAY_TC { get; set; }
    public double? OT_SUNDAYNIGHT_TC { get; set; }
    public double? OT_HOLIDAY_TC { get; set; }
    public double? OT_HOLIDAY_NIGHT_TC { get; set; }
    public double? OT_WEEKDAY_SC { get; set; }
    public double? OT_WEEKNIGHT_SC { get; set; }
    public double? OT_SUNDAY_SC { get; set; }
    public double? OT_SUNDAYNIGHT_SC { get; set; }
    public double? OT_HOLIDAY_SC { get; set; }
    public double? OT_HOLIDAY_NIGHT_SC { get; set; }
    public bool? IS_NB_TC { get; set; }
    public bool? IS_NB_SC { get; set; }
    public double? OT_TOTAL_CONVERT_PAY { get; set; }
    public double? OT_TOTAL_CONVERT_NB { get; set; }
    public bool? IS_EDIT { get; set; }
    public double? MINUTE_OUT { get; set; }
    public string? HR_COMMENT { get; set; }
    public string? MODIFIED_DETAIL { get; set; }
    public bool? IS_REGISTER_LATE { get; set; }
    public bool? IS_REGISTER_COMEBACKOUT { get; set; }
    public double? TOTAL_MINUTE_OUT { get; set; }
    public bool? IS_NO_LATE_COMEBACKOUT { get; set; }
    public bool? IS_CONFIRM { get; set; }
    public double? MINUTE_DM_DK { get; set; }
    public double? MINUTE_VS_DK { get; set; }
    public long? SHIFT_ID_OT { get; set; }
    public bool? IS_EDIT_INOUT { get; set; }
    public bool? IS_OUT_REGISTER { get; set; }
    public bool? IS_AN_CA { get; set; }
    public bool? IS_HOLIDAY { get; set; }
    public bool? IS_HOLIDAY_NEXT { get; set; }
    public bool? IS_HOLIDAY_LT { get; set; }
    public bool? IS_OFF_PRE { get; set; }
    public bool? IS_OFF_NEXT { get; set; }
    public double? GIO_VE_MUON { get; set; }
    public double? OT_WEEKDAY_TT { get; set; }
    public double? OT_WEEKNIGHT_TT { get; set; }
    public double? OT_SUNDAY_TT { get; set; }
    public double? OT_SUNDAYNIGHT_TT { get; set; }
    public double? OT_HOLIDAY_TT { get; set; }
    public double? OT_HOLIDAY_NIGHT_TT { get; set; }
    public DateTime? VALIN1_TT { get; set; }
    public DateTime? VALIN4_TT { get; set; }
    public long? SHIFT_MANUAL_ID { get; set; }
    public DateTime? VAL_IN { get; set; }
    public DateTime? VAL_OUT { get; set; }
    public bool? IS_OFF_DN1 { get; set; }
    public bool? IS_CASE_OT { get; set; }
    public string? REASON { get; set; }
    public long? CODE_COLOR { get; set; }
}
