using System.ComponentModel.DataAnnotations.Schema;

namespace API.Entities;
[Table("AT_TIMESHEET_MONTHLY")]
public partial class AT_TIMESHEET_MONTHLY
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long ID { get; set; }
    public long? EMPLOYEE_ID { get; set; }
    public long? ORG_ID { get; set; }
    public long? POSITION_ID { get; set; }
    public double? WORKING_E { get; set; }
    public DateTime? CREATED_DATE { get; set; }
    public string? CREATED_BY { get; set; }
    public DateTime? UPDATED_DATE { get; set; }
    public string? UPDATED_BY { get; set; }
    public long? PERIOD_ID { get; set; }
    public long? DECISION_ID { get; set; }
    public long? PA_EMPLOYEE_OBJECT_ID { get; set; }
    public long? STAFF_RANK_ID { get; set; }
    public DateTime? FROM_DATE { get; set; }
    public DateTime? END_DATE { get; set; }
    public double? TOTAL_WORKING_XJ { get; set; }
    public double? TOTAL_TS_V { get; set; }
    public double? TOTAL_WORKING { get; set; }
    public double? WORKING_ADD { get; set; }
    public DateTime? DECISION_START { get; set; }
    public DateTime? DECISION_END { get; set; }
    public double? WORKING_TV { get; set; }
    public double? WORKING_A { get; set; }
    public double? WORKING_NH { get; set; }
    public double? WORKING_R { get; set; }
    public double? WORKING_S { get; set; }
    public double? WORKING_NB { get; set; }
    public double? WORKING_J { get; set; }
    public double? WORKING_TS { get; set; }
    public double? WORKING_D { get; set; }
    public double? WORKING_V { get; set; }
    public double? WORKING_KT { get; set; }
    public double? WORKING_L { get; set; }
    public double? WORKING_DS { get; set; }
    public double? WORKING_H { get; set; }
    public double? TOTAL_NB { get; set; }
    public double? OT_TOTAL_CONVERT { get; set; }
    public double? TOTAL_OT_WEEKDAY { get; set; }
    public double? TOTAL_OT_SUNDAY { get; set; }
    public double? TOTAL_OT_SUNDAYNIGTH { get; set; }
    public double? TOTAL_OT_HOLIDAY { get; set; }
    public double? TOTAL_OT_HOLIDAY_NIGTH { get; set; }
    public double? TOTAL_OT_STORE { get; set; }
    public double? WORKING_X { get; set; }
    public double? WORKING_F { get; set; }
    public double? WORKING_Q { get; set; }
    public double? WORKING_NV { get; set; }
    public double? WORKING_P { get; set; }
    public double? WORKING_O { get; set; }
    public double? WORKING_DA { get; set; }
    public double? WORKING_VS { get; set; }
    public double? WORKING_RO { get; set; }
    public double? WORKING_CT { get; set; }
    public double? WORKING_KO { get; set; }
    public double? WORKING_NH1 { get; set; }
    public double? OT_TOTAL_CONVERT_PAY { get; set; }
    public double? OT_TOTAL_CONVERT_NB { get; set; }
    public double? TOTAL_HL { get; set; }
    public double? TOTAL_KL { get; set; }
    public double? TOTAL_BHXH { get; set; }
    public double? TOTAL_OFF_KL { get; set; }
    public double? TOTAL_LATE_COMEBACKOUT_DK { get; set; }
    public double? TOTAL_LATE_COMEBACKOUT_KDK { get; set; }
    public double? CHUYEN_CAN { get; set; }
    public double? OT_150_NQD { get; set; }
    public double? OT_210_NQD { get; set; }
    public double? OT_200_NQD { get; set; }
    public double? OT_270_NQD { get; set; }
    public double? OT_300_NQD { get; set; }
    public double? OT_390_NQD { get; set; }
    public double? TOTAL_PAY_OT_NQD { get; set; }
    public double? TOTAL_LC { get; set; }
    public double? TOTAL_WORKING_HL { get; set; }
    public double? TOTAL_OT_WEEKNIGHT { get; set; }
    public double? TOTAL_SHIFT_S3 { get; set; }
    public double? OT150 { get; set; }
    public double? OT210 { get; set; }
    public double? OT200 { get; set; }
    public double? OT270 { get; set; }
    public double? OT300 { get; set; }
    public double? OT390 { get; set; }
    public double? WORKING_STANDARD { get; set; }
    public double? P_MAX_PAYOT { get; set; }
    public double? WORKING_STANDARD_GD { get; set; }
    public double? IS_SANCONG { get; set; }
    public double? WORKING_LCB { get; set; }
    public double? WORKING_CTN { get; set; }
    public double? TOTAL_LATE { get; set; }
    public double? TOTAL_COMEBACKOUT { get; set; }
    public double? TOTAL_DM_PHAT { get; set; }
    public double? TOTAL_VS_PHAT { get; set; }
    public double? WORKING_L_OFF { get; set; }
    public double? IS_TRAILWORK { get; set; }
}
